on:
  push:
    branches-ignore:
      - 'citest-*'
    tags-ignore:
      - '**'
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'push' }}
    uses: cyberrangecz/ci-images/.github/workflows/test.yml@master
    with:
      tofu_import_image: true
      use_images_runner: false
    secrets: inherit
